### ISSUE TITLE
SetTerrainMaterialSize crashes/query

### ISSUE THREAD

**Issue by DruggedBunny** [blitz-research/libsgd#1]
Just run into this -- running seems to crash either at the point of calling SetTerrainMaterialSize (when the asset is remote, from SGD://), or on exit when it's local (using [Ground037](https://ambientcg.com/view?id=Ground037) -- the 1K JPG version in a local blitzmax\materials folder, main file placed in blitzmax\examples):

```
Include "../sgd.bmx"

Const FULL_SCREEN:Int = False

Const CAMERA_PITCH_INVERT:Int = False ' True to flip look-up/down on Xbox pad

' Normally place sgd_dynamic.dll in same folder and just
' call SGD.LoadSGD to import LibSGD. Distribution demo requires
' custom path, hence:

SGD.LoadSGD "../../lib/sgd_dynamic.dll"

SGD.Init ' Normal SGD setup call

' --------
' WINDOW:
' --------

Local flags:Int = SGD.WINDOW_FLAGS_RESIZABLE

If FULL_SCREEN
	flags = SGD.WINDOW_FLAGS_FULLSCREEN
EndIf

SGD.CreateWindow (1280, 720, "Min Demo - WASD/Shift plus CURSORS", flags)

' --------
' SKYBOX:
' --------

Local sky_map_path:String = "sgd://envmaps/sunnysky-cube.png"

Local sky_texture:Int = SGD.LoadCubeTexture (sky_map_path, SGD.TEXTURE_FORMAT_ANY, SGD.TEXTURE_FLAGS_DEFAULT)

SGD.SetEnvTexture sky_texture

Local skybox:Int = SGD.CreateSkybox (sky_texture)
SGD.SetSkyboxRoughness skybox, 0.3

' ----------
' LIGHTING:
' ----------

SGD.SetAmbientLightColor 0.025, 0.05, 0.0375, 1.0

Local light:Int = SGD.CreateDirectionalLight ()

' Light details:

SGD.SetLightRange light, 1000.0
SGD.SetLightShadowsEnabled (light, True) ' CASTING SHADOW
SGD.SetLightColor light, 1.0, 1.0, 1.0, 1.0

SGD.MoveEntity light, -5, 5.0, 7.5
SGD.TurnEntity light, -22.5, -120, 0

Local ground_material_path:String = "sgd://materials/PavingStones131_1K-JPG"
'Local ground_material_path:String = "materials\Ground037_1K-JPG"

Local ground_material:Int = SGD.LoadPBRMaterial (ground_material_path)

Local ground:Int = SGD.CreatePlane (ground_material)

' Scale texture...

Local ground_scale:Int = 50

SGD.SetTerrainMaterialSize ground, 50

' --------
' CAMERA:
' --------

Local camera:Int = SGD.CreatePerspectiveCamera ()

SGD.SetCameraNear camera, 0.05		' Allow extreme closeups!
SGD.MoveEntity camera, 0, 1.5, 0	' Positioning

' Window events variables...

Local events:Int
Local quit:Int = False

' Camera movement variables...

Local pitch:Double = 0.0
Local yaw:Double = 0.0
Local strafe:Double = 0.0
Local rise:Double = 0.0
Local z:Double = 0.0

Repeat

	' Get window events...
	
	events = SGD.PollEvents ()
	
	' Check for ESC key or window close gadget-hit...
	
	If SGD.IsKeyHit (SGD.KEY_ESCAPE) Or events & SGD.EVENT_MASK_CLOSE_CLICKED
		quit = True
	EndIf
	
	' No gamepad input, use keys (er, which turned out better):
	
	' LEFT/RIGHT cursors: camera strafe...
	
	If SGD.IsKeyDown (SGD.KEY_LEFT)
		yaw = yaw + 0.1
		If yaw > 1.5 Then yaw = 1.5
	Else
		If SGD.IsKeyDown (SGD.KEY_RIGHT)
			yaw = yaw - 0.1
			If yaw < -1.5 Then yaw = -1.5
		EndIf
	EndIf

	' Pitch inversion option...
	
	Local pitcher:Float = 1.0
	
	If CAMERA_PITCH_INVERT Then pitcher = -1.0
	
	' UP/DOWN cursors: camera tilt...
	
	If SGD.IsKeyDown (SGD.KEY_UP)
		pitch = pitch - 0.1 * pitcher
		If pitch < -1.5 Then pitch = -1.5
	Else
		If SGD.IsKeyDown (SGD.KEY_DOWN)
			pitch = pitch + 0.1 * pitcher
			If pitch > 1.5 Then pitch = 1.5
		EndIf
	EndIf

	' Camera boost with LEFT SHIFT...
	
	Local shifted:Float = 1.0
	
	If SGD.IsKeyDown (SGD.KEY_LEFT_SHIFT)
		shifted = 2.0
	EndIf
	
	' A/D keys: strafe left/right...

	If SGD.IsKeyDown (SGD.KEY_A)
		strafe = strafe - 0.01 * shifted
		If strafe < -0.1 * shifted Then strafe = -0.1 * shifted
	Else
		If SGD.IsKeyDown (SGD.KEY_D)
			strafe = strafe + 0.1 * shifted
			If strafe > 0.1 * shifted Then strafe = 0.1 * shifted
		EndIf
	EndIf

	' W/S keys: forward/back...

	If SGD.IsKeyDown (SGD.KEY_W)
		z = z + 0.01 * shifted
		If z > 0.1 * shifted Then z = 0.1 * shifted
	Else
		If SGD.IsKeyDown (SGD.KEY_S)
			z = z - 0.01 * shifted
			If z < -0.1 * shifted Then z = -0.1 * shifted
		EndIf
	EndIf

	' Diminish all movement towards 0...
	
	pitch	= Util.Diminish (pitch, 0.03)
	yaw		= Util.Diminish (yaw, 0.03)
	strafe	= Util.Diminish (strafe, 0.0015)
	rise	= Util.Diminish (rise, 0.0015)
	z		= Util.Diminish (z, 0.0015)

	' Update camera...
	
	SGD.TurnEntity camera, pitch, 0, 0
	SGD.RotateEntity camera, 0, yaw, 0
	SGD.MoveEntity camera, strafe, rise, z
	
	' Render/show!
	
	SGD.RenderScene
	SGD.Present
	
Until quit

SGD.Terminate()

End

' Utility functions...

Type Util

	' Just to tidy up Rnd Double warnings!

	Function RndF:Float (minValue:Float = 1, maxValue:Float = 0)
		Return Float (Rnd (minValue, maxValue))
	End Function

	' Reduce value towards 0 by amount (eg. 0.01)...
	
	Function Diminish:Double (value:Double, amount:Double)
		If Abs (value) <= Abs (amount) Then Return 0.0
		value = value - (amount * Sgn (value))
		Return value
	End Function

End Type
```

I'm also a bit unclear as to what this is meant to do -- is it scaling the texture, as I was hoping? And if so, why's it an integer value?

I tried initially using TransformTexCoords but that crashes with ground used as mesh (oh, duhhh), so guess that's what this is meant for, but I'm surprised it's not a float value in sgd_SetTerrainMaterialSize(SGD_Terrain terrain, int materialSize).

(Looks like GitHub doesn't like the code! EDIT: Fixed, they used single back-quote instead of triples!)

**Comment by DruggedBunny** [comment]
Just tried this again today and realised I hadn't posted how it crashed -- with the local material, I get (after driver output):

```
2024-10-27 14:50:42.140 [  4768] core/fetch.cpp (62) : Asset cache initialized
2024-10-27 14:50:42.146 [  4768] graphics/core/textureutil.cpp (271) : ### Loading STB 8
2024-10-27 14:50:43.414 [  4768] graphics/core/textureutil.cpp (271) : ### Loading STB 8
2024-10-27 14:50:43.830 [  4768] core/fileio.cpp (12) : File IO Error: IO error examining file "materials/Ground037_1K-JPG/Ground037_1K-JPG_Metalness.jpg" file: C:\Users\marks\dev\libsgd\core\fileio.cpp line: 64
2024-10-27 14:50:43.839 [  4768] graphics/core/textureutil.cpp (271) : ### Loading STB 8
2024-10-27 14:50:43.861 [  4768] graphics/core/textureutil.cpp (271) : ### Loading STB 8
2024-10-27 14:50:43.890 [  4768] graphics/core/textureutil.cpp (271) : ### Loading STB 8

```

Today it won't get to the point of crashing on exit, so with the sgd:: material it's crashing at the same point (SetTerrainMaterialSize) and saying:

```
2024-10-27 14:54:33.257 [ 11276] core/fetch.cpp (62) : Asset cache initialized
2024-10-27 14:54:33.259 [ 11276] graphics/core/textureutil.cpp (271) : ### Loading STB 8
2024-10-27 14:54:34.523 [ 11276] graphics/core/textureutil.cpp (271) : ### Loading STB 8
2024-10-27 14:54:36.091 [ 11276] core/fileio.cpp (12) : File IO Error: CURL http request failed: 404 file: C:\Users\marks\dev\libsgd\core\fetch.cpp line: 151
2024-10-27 14:54:36.092 [ 11276] graphics/core/textureutil.cpp (271) : ### Loading STB 8
2024-10-27 14:54:36.111 [ 11276] graphics/core/textureutil.cpp (271) : ### Loading STB 8
2024-10-27 14:54:36.133 [ 11276] graphics/core/textureutil.cpp (271) : ### Loading STB 8

```

Note different fetch.cpp line.

While typing this, sometimes it runs but does the crash-on-exit (seems to be more with the local file, and it still shows the http request error, even though the texture appears to have loaded), and sometimes it just silently exits...

**Comment by DruggedBunny** [comment]
Interesting, just noticed 'IO error examining file "materials/Ground037_1K-JPG/Ground037_1K-JPG_Metalness.jpg"' and found that file doesn't exist in [Ground037](https://ambientcg.com/view?id=Ground037) ... and that filename doesn't appear in the .mtlx or .usdc files, so not sure why it's trying to locate that?

**Comment by DruggedBunny** [comment]
... and if I clone Tiles019_1K-JPG locally, it also logs error looking for _Metalness, though the material otherwise loads, just get the crash on exit:

`
2024-10-27 15:20:27.846 [ 10904] core/fileio.cpp (12) : File IO Error: IO error examining file "materials/Tiles019_1K-JPG/Tiles019_1K-JPG_Metalness.jpg" file: C:\Users\marks\dev\libsgd\core\fileio.cpp line: 64
`

Thought the exit crash might have been in SGD.Terminate but it still crashes if that's commented-out.

At the moment, using sgd://materials/Tiles019_1K-JPG is giving the 404 error (presumably looking for _Metalness, could do with adding URL to that error, but presumably that's working as intended, just doesn't load if it's not there), but then closing silently.

**Comment by DruggedBunny** [comment]
Finally (for what it's worth), using sgd://materials/Tiles019_1K-JPG and removing _SGD.SetTerrainMaterialSize ground, x_ loads (with the 404 error) and exits normally.

**Comment by DruggedBunny** [comment]
When I say 'finally'... cough. Trying this instead of LoadPBRMaterial, I get the same crash-on-exit, but also it's not tiling:

```
Local ground_material:Int = SGD.LoadPrelitMaterial ("materials\grass.png")
Local ground:Int = SGD.CreatePlane (ground_material)
```

![loadprelit](https://github.com/user-attachments/assets/4ef2f5ef-7024-4fc9-a287-ca619e9f058d)

Using...

![grass](https://github.com/user-attachments/assets/48ddddc4-ae4a-4c17-a193-ed24ab4e4e20)

**Comment by blitz-research** [comment]
Are you sure this is right?
```
Local ground:Int = SGD.CreatePlane (ground_material)

' Scale texture...

Local ground_scale:Int = 50

SGD.SetTerrainMaterialSize ground, 50
```
SetTerrainMaterialSize if for terrains, not planes, although the runtime should be picking this up so maybe it's wrong in the interface somewhere, will take a look.

Also, yes, size should be a float, will fix.

>Interesting, just noticed 'IO error examining file "materials/Ground037_1K-JPG/Ground037_1K-JPG_Metalness.jpg"' and found that file doesn't exist

There's a thread about this in bug reports - basically, curl doesn't have a way to do anything like 'FileExists' so I just tries all possible textures for a material. The error is not fatal (or shouldn't be) and will be fixed once there's a material 'format' implemented.

> Trying this instead of LoadPBRMaterial, I get the same crash-on-exit, but also it's not tiling:

This is because LoadPrelitMaterial defaults to 'clamp' flags, as it assumes the material will be used for images/sprites. The o0bvious fix is to add format/flags to LoadPrelitMaterial, but not sure yet...I'm in the process of finalizing a material format and how materials work now.

**Comment by DruggedBunny** [comment]
> SetTerrainMaterialSize if for terrains, not planes

Oh, gawd, so it is! I was thinking of the plane as my 'terrain'... never even noticed the difference somehow, sorry! The rest obviously makes sense now. Thanks Mark.

**Comment by blitz-research** [comment]
Actually, I think a SetPlaneMaterialSize makes sense too. You can achieve this by using scaling, but that also messes up parenting to a degree (until I add some 'noinherit' flags anyway).

**Comment by DruggedBunny** [comment]
One thing I'm a bit unsure about (looked for this yesterday) -- how come these materials need separate sizing, was wondering why it wasn't just a case of applying a scaling factor to the material? But I couldn't see a way to do that, unless there's a material float to set? Is this like changing 'normal' meshes' u/v settings?

Just checked and can't see a texture scale option either -- I see Blitz3D had ScaleTexture? But I think my grasp is a bit limited on all this! I suspect in old B3D we would have scaled the texture being applied to a plane.

**Comment by blitz-research** [comment]
>how come these materials need separate sizing, was wondering why it wasn't just a case of applying a scaling factor to the material? 

I think I will probably add this, I was playing around with it yesterday for PBR shaders and the overhead wont be huge. But the main reason I'm reluctant to just throw 1001 features at shaders is because it slows down rendering for everyone, whether or not they use those features. eg: if a build a runtime equaivalent of TransformTexCoords into all material shaders, that slows down *ALL* rendering for everyone, whether or not they use it, and 93% of meshes eg: loaded from GLBs wont use it. Ditto animated/rotating textures and a ton of stuff that'd be nice to have.

You can '#ifdef' out features that aren't used out to a degree (eg: if scale is 1, don't compile the code that multiplies by scale, or have 'enable' switches), but it's not easy as shader languages offer no help to do this (in wgsl, you don't even get #ifdef preprocessing, although I've added that), so you need to somehow detetect when to do this and compile different versions of shaders for every possible combination of enabled features (without pissing people off with mysterious pauses while new shaders build!). Not impossible and I've hacked in conditional shader compilation in some places, but I've not really got any 'system' in place for handling 'conditional shader features' I guess I'd call them. Would love to work on a framework like this one day but have about 100 more important things to do right now.

In Blitz3D, there were no shaders, and I think the 'texture matrices' were built into D3D7, can't remember if you had to enable them or not. But comparing D3D7 with WebGPU is like comparing BASIC with C++, there's just a ton of stuff that doesn't work even remotely the same, so commands that made sense in Blitz3D may not always make sense in SGD. Texture scale may make sense with an API that directly supports it, but it gets a whole lot more complex if you want it to work with an arbitrary collection shaders (including custom shader) with arbitrary numbers of textures, in which case Material scale may be the best compromise.

**Comment by DruggedBunny** [comment]
Whoa, thanks for the deep write-up! I obviously have little grasp of the costs involved in all this stuff, so that helps me gain some perspective... I suppose in many cases we just have to create media up-front in the necessary scale (or whatever other factors we might have previously tweaked after loading media).
